# Generated by Django 4.2.4 on 2023-09-03 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('Incomplete', 'Incomplete'), ('Complete', 'Complete')], default='Incomplete', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('priority', models.CharField(choices=[('0', ' 0️⃣'), ('1', ' 1️⃣'), ('2', ' 2️⃣'), ('3', ' 3️⃣'), ('4', ' 4️⃣'), ('5', ' 5️⃣'), ('6', ' 6️⃣'), ('7', ' 7️⃣'), ('8', ' 8️⃣')], max_length=50)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('Heigh', 'Heigh')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
